grounding:
  max_results: 0
include: []
max_completion_tokens: 50000
model: gemini-1.5-flash
prompt_template: null
provider: google
provider_urls:
  google: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent
  openai: https://api.openai.com/v1/responses
  openaidp: https://api.openai.com/v1/responses
reasoning:
  effort: low
test:
  file_a: test/input/sample_utf8.txt
  file_b: test/prompts/standard_prompt.txt
  out: test/output/<file_b_stem>.<model_name>.fpf.response.md
web_search:
  search_context_size: low
  search_prompt: Perform a focused web search for up-to-date information relevant
    to the user's request. Summarize the most relevant findings and include citation
    links.
